updates

diff --git a/lib/bin/brew b/lib/bin/brew
--- a/lib/bin/brew
+++ b/lib/bin/brew
@@ -1,37 +1,35 @@
-# Upgrade any already-installed formulae
-brew update
-brew upgrade
-brew upgrade
-
-# Install GNU core utilities (those that come with OS X are outdated)
-# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
-brew install coreutils
-# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
-# Install Bash 4
-brew install bash
-
-brew install findutils
-brew tap homebrew/dupes
-brew install homebrew/dupes/grep
-brew tap josegonzalez/homebrew-php
-brew install php55
-brew tap homebrew/versions
-brew install lua52
-brew tap caskroom/fonts
-brew tap caskroom/versions
-
-fonts=(
+readonly brew=/usr/local/bin/brew
+readonly fonts=(
   font-m-plus
   font-clear-sans
   font-roboto
   font-open
+  font-open-sans-condensed
+  font-pt-sans
+  font-pt-sans-narrow
+  font-pt-mono
+  font-pt-serif
+  font-oswald
+  font-droid-sans
+  font-lato
+  font-arvo
+  font-playfair-display
+  font-ubuntu
+  font-montserrat
+  font-raleway
+  font-oxygen
+  font-merriweather
+  font-old-standard-tt
+  font-abril-fatface
 )
 
-bins=(
+readonly bins=(
   zsh
   mysql
   emacs
   git
+  curl
+  gpg
   reattach-to-user-namespace
   hub
   ffmpeg
@@ -47,7 +45,7 @@ bins=(
   parallel
   htop
   node
-  wget --enable-iri
+  'wget --enable-iri'
   ack
   lynx
   youtube-dl
@@ -57,11 +55,12 @@ bins=(
   rhino
   webkit2png
   zopfli
+  httpie
   p7zip
   ngrep
 )
 
-apps=(
+readonly apps=(
   dropbox
   google-chrome
   google-chrome-canary
@@ -74,7 +73,9 @@ apps=(
   textmate
   dash
   the-unarchiver
-  tor-browser
+  abobe-creative-cloud
+  colorpicker
+  torbrowser
   virtualbox
   vlc
   xquartz
@@ -91,31 +92,78 @@ apps=(
   mono-mdk
   firefox
   perian
+  bee
   silverlight
   transmit
   trailrunner
   vagrant
-  eclipse-ide
   flip4mac
-  bitcoin
+  bitcoin-core
+  gpgtools
   charles
 )
-# Install binaries
-echo "installing bins..."
-brew  install ${bins[@]}
 
-# Install apps
-echo "installing apps..."
-brew cask install ${apps[@]}
+function command_exists () {
+    type "$1" &> /dev/null ;
+}
 
-# Install fonts
-echo "installing fonts..."
-brew cask install ${fonts[@]}
+function main () {
+  $brew tap homebrew/versions
+  $brew tap homebrew/dupes
+  $brew tap caskroom/fonts
+  $brew tap caskroom/versions
+  $brew tap josegonzalez/homebrew-php
+  # Upgrade any already-installed formulae
+  $brew update
+  $brew upgrade
+  
+  # Install binaries
+  echo -e "\nInstalling bins..."
+  # Install GNU core utilities (those that come with OS X are outdated)
+  # Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
+  $brew install coreutils
+  # Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
+  # Install Bash 4
+  $brew install bash
+  $brew install findutils
+  $brew install homebrew/dupes/grep
+  $brew install php55
+  $brew install lua52
+  
+  for binary in "${bins[@]}"
+  do
+    if ! command_exists $binary; then
+      echo -e "$binary not found, installing..."
+      #$brew install ${bins[@]}
+    else
+      echo -e "$binary already installed"
+    fi
+  done
 
-# Cleanup
-brew cleanup
-brew cask cleanup
+  # Install apps
+  echo -e "\nInstalling apps..."
+  $brew cask install ${apps[@]}
 
-# Doctor
-brew cask doctor
-brew doctor
+  # Install fonts
+  echo -e "\nInstalling fonts..."
+  $brew cask install ${fonts[@]}
+
+  if command_exists bundle; then
+      echo -e "\nBundler Installed... continuing"
+  else
+      sudo gem install bundler
+  fi
+
+  # Cleanup
+  $brew cleanup
+  $brew cask cleanup
+
+  # Doctor
+  $brew cask doctor
+  $brew doctor
+}
+
+main
+unset command_exists
+unset main
+exit 0
